export declare type IconType =
  | 'music-tone-alt'
  | 'rocket'
  | 'cup-2'
  | 'drawer'
  | 'folder-alt'
  | 'pin'
  | 'chemistry'
  | 'shield'
  | 'game-controller'
  | 'plane'
  | 'organization'
  | 'call-end'
  | 'call-in'
  | 'call-out'
  | 'camrecorder'
  | 'bag'
  | 'umbrella'
  | 'basket'
  | 'basket-loaded'
  | 'calculator'
  | 'cup'
  | 'earphones'
  | 'earphones-alt'
  | 'handbag'
  | 'wallet'
  | 'present'
  | 'badge'
  | 'eyeglass'
  | 'graduation'
  | 'mouse'
  | 'speedometer'
  | 'graph'
  | 'clock'
  | 'wrench'
  | 'volume-2'
  | 'vector'
  | 'arrow-down'
  | 'anchor'
  | 'action-undo'
  | 'action-redo'
  | 'accessibility'
  | 'user-following'
  | 'volume-off'
  | 'support'
  | 'volume-1'
  | 'user'
  | 'user-unfollow'
  | 'user-follow'
  | 'user-female'
  | 'share-alt'
  | 'trash'
  | 'target'
  | 'question-circle'
  | 'tag'
  | 'star'
  | 'screen-tablet'
  | 'speech'
  | 'size-fullscreen'
  | 'size-actual'
  | 'shuffle'
  | 'power'
  | 'share'
  | 'settings'
  | 'picture'
  | 'screen-smartphone'
  | 'screen-desktop'
  | 'satellite'
  | 'reload'
  | 'refresh'
  | 'magnifier'
  | 'puzzle'
  | 'printer'
  | 'login'
  | 'plus-circle'
  | 'pie-chart'
  | 'options-vertical'
  | 'people'
  | 'pencil'
  | 'paper-plane'
  | 'heart'
  | 'options'
  | 'notebook'
  | 'note'
  | 'music-tone'
  | 'minus-circle'
  | 'microphone'
  | 'menu'
  | 'map'
  | 'like'
  | 'loop'
  | 'logout'
  | 'cursor-move'
  | 'lock-open'
  | 'lock'
  | 'location-pin'
  | 'list'
  | 'link'
  | 'folder'
  | 'layers'
  | 'key'
  | 'info-circle'
  | 'hourglass'
  | 'home'
  | 'film'
  | 'grid'
  | 'globe-alt'
  | 'globe'
  | 'frame'
  | 'crop'
  | 'flag'
  | 'fire'
  | 'energy'
  | 'feed'
  | 'eye'
  | 'exclamation-circle'
  | 'event'
  | 'equalizer'
  | 'envelope-open'
  | 'envelope-letter'
  | 'envelope'
  | 'directions'
  | 'docs'
  | 'doc'
  | 'dislike'
  | 'control-play'
  | 'direction'
  | 'close-circle'
  | 'cursor'
  | 'arrow-left'
  | 'control-start'
  | 'control-rewind'
  | 'camera'
  | 'control-pause'
  | 'control-forward'
  | 'control-end'
  | 'compass'
  | 'cloud-upload'
  | 'cloud-download'
  | 'arrow-up-circle'
  | 'x'
  | 'check-circle'
  | 'chart'
  | 'calendar'
  | 'bulb'
  | 'bubbles'
  | 'bubble'
  | 'briefcase'
  | 'book-open'
  | 'arrow-right'
  | 'bell'
  | 'ban-circle'
  | 'arrow-left-circle'
  | 'arrow-up'
  | 'arrow-right-circle'
  | 'arrow-down-circle';

export const ICON_TYPES: { [key in IconType]: IconType } = {
  'music-tone-alt': 'music-tone-alt',
  rocket: 'rocket',
  'cup-2': 'cup-2',
  drawer: 'drawer',
  'folder-alt': 'folder-alt',
  pin: 'pin',
  chemistry: 'chemistry',
  shield: 'shield',
  'game-controller': 'game-controller',
  plane: 'plane',
  organization: 'organization',
  'call-end': 'call-end',
  'call-in': 'call-in',
  'call-out': 'call-out',
  camrecorder: 'camrecorder',
  bag: 'bag',
  umbrella: 'umbrella',
  basket: 'basket',
  'basket-loaded': 'basket-loaded',
  calculator: 'calculator',
  cup: 'cup',
  earphones: 'earphones',
  'earphones-alt': 'earphones-alt',
  handbag: 'handbag',
  wallet: 'wallet',
  present: 'present',
  badge: 'badge',
  eyeglass: 'eyeglass',
  graduation: 'graduation',
  mouse: 'mouse',
  speedometer: 'speedometer',
  graph: 'graph',
  clock: 'clock',
  wrench: 'wrench',
  'volume-2': 'volume-2',
  vector: 'vector',
  'arrow-down': 'arrow-down',
  anchor: 'anchor',
  'action-undo': 'action-undo',
  'action-redo': 'action-redo',
  accessibility: 'accessibility',
  'user-following': 'user-following',
  'volume-off': 'volume-off',
  support: 'support',
  'volume-1': 'volume-1',
  user: 'user',
  'user-unfollow': 'user-unfollow',
  'user-follow': 'user-follow',
  'user-female': 'user-female',
  'share-alt': 'share-alt',
  trash: 'trash',
  target: 'target',
  'question-circle': 'question-circle',
  tag: 'tag',
  star: 'star',
  'screen-tablet': 'screen-tablet',
  speech: 'speech',
  'size-fullscreen': 'size-fullscreen',
  'size-actual': 'size-actual',
  shuffle: 'shuffle',
  power: 'power',
  share: 'share',
  settings: 'settings',
  picture: 'picture',
  'screen-smartphone': 'screen-smartphone',
  'screen-desktop': 'screen-desktop',
  satellite: 'satellite',
  reload: 'reload',
  refresh: 'refresh',
  magnifier: 'magnifier',
  puzzle: 'puzzle',
  printer: 'printer',
  login: 'login',
  'plus-circle': 'plus-circle',
  'pie-chart': 'pie-chart',
  'options-vertical': 'options-vertical',
  people: 'people',
  pencil: 'pencil',
  'paper-plane': 'paper-plane',
  heart: 'heart',
  options: 'options',
  notebook: 'notebook',
  note: 'note',
  'music-tone': 'music-tone',
  'minus-circle': 'minus-circle',
  microphone: 'microphone',
  menu: 'menu',
  map: 'map',
  like: 'like',
  loop: 'loop',
  logout: 'logout',
  'cursor-move': 'cursor-move',
  'lock-open': 'lock-open',
  lock: 'lock',
  'location-pin': 'location-pin',
  list: 'list',
  link: 'link',
  folder: 'folder',
  layers: 'layers',
  key: 'key',
  'info-circle': 'info-circle',
  hourglass: 'hourglass',
  home: 'home',
  film: 'film',
  grid: 'grid',
  'globe-alt': 'globe-alt',
  globe: 'globe',
  frame: 'frame',
  crop: 'crop',
  flag: 'flag',
  fire: 'fire',
  energy: 'energy',
  feed: 'feed',
  eye: 'eye',
  'exclamation-circle': 'exclamation-circle',
  event: 'event',
  equalizer: 'equalizer',
  'envelope-open': 'envelope-open',
  'envelope-letter': 'envelope-letter',
  envelope: 'envelope',
  directions: 'directions',
  docs: 'docs',
  doc: 'doc',
  dislike: 'dislike',
  'control-play': 'control-play',
  direction: 'direction',
  'close-circle': 'close-circle',
  cursor: 'cursor',
  'arrow-left': 'arrow-left',
  'control-start': 'control-start',
  'control-rewind': 'control-rewind',
  camera: 'camera',
  'control-pause': 'control-pause',
  'control-forward': 'control-forward',
  'control-end': 'control-end',
  compass: 'compass',
  'cloud-upload': 'cloud-upload',
  'cloud-download': 'cloud-download',
  'arrow-up-circle': 'arrow-up-circle',
  x: 'x',
  'check-circle': 'check-circle',
  chart: 'chart',
  calendar: 'calendar',
  bulb: 'bulb',
  bubbles: 'bubbles',
  bubble: 'bubble',
  briefcase: 'briefcase',
  'book-open': 'book-open',
  'arrow-right': 'arrow-right',
  bell: 'bell',
  'ban-circle': 'ban-circle',
  'arrow-left-circle': 'arrow-left-circle',
  'arrow-up': 'arrow-up',
  'arrow-right-circle': 'arrow-right-circle',
  'arrow-down-circle': 'arrow-down-circle',
};
