#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

eslint --ext .ts,.html . --fix --ignore-path .gitignore && prettier "**/*.ts" --write --ignore-path .gitignore && stylelint "**/*.css" --fix --ignore-path .gitignore
