import { getBasePath } from '../../../utilities/base-path.js';

export const ICON_SIZES: { [key: string]: string } = {
  xxSmall: 'xx-small',
  xSmall: 'x-small',
  small: 'small',
  medium: 'medium',
  large: 'large',
  xLarge: 'x-large',
  xxLarge: 'xx-large',
  xxxLarge: 'xxx-large',
  xxxxLarge: 'xxxx-large',
};

export const ICON_TYPES: { [key: string]: string } = {
  accessibility: 'accessibility',
  x: 'x',
  brightnessLow: 'brightness_low',
  userRemove: 'user-remove',
  user: 'user',
  shield: 'shield',
  screenTablet: 'screen-tablet',
  screenSmartphone: 'screen-smartphone',
  screenDesktop: 'screen-desktop',
  userCheck: 'user-check',
  graduation: 'graduation',
  fire: 'fire',
  eyeglass: 'eyeglass',
  userPlus: 'user-plus',
  cursorMove: 'cursor-move',
  crop: 'crop',
  bell: 'bell',
  speech: 'speech',
  pin: 'pin',
  layers: 'layers',
  frame: 'frame',
  people: 'people',
  trash: 'trash',
  sizeActual: 'size-actual',
  share: 'share',
  question: 'question',
  microphone: 'microphone',
  sizeFullscreen: 'size-fullscreen',
  home: 'home',
  grid: 'grid',
  equalizer: 'equalizer',
  note: 'note',
  calender: 'calender',
  arrowUpCircle: 'arrow-up-circle',
  arrowRightCircle: 'arrow-right-circle',
  arrowLeftCircle: 'arrow-left-circle',
  arrowDownCircle: 'arrow-down-circle',
  check: 'check',
  close: 'close',
  cloudDownload: 'cloud-download',
  cloudUpload: 'cloud-upload',
  eye: 'eye',
  info: 'info',
  link: 'link',
  lock: 'lock',
  lockOpen: 'lock-open',
  magnifier: 'magnifier',
  magnifierAdd: 'magnifier-add',
  magnifierRemove: 'magnifier-remove',
  paperClip: 'paper-clip',
  refresh: 'refresh',
  reload: 'reload',
  settings: 'settings',
  star: 'star',
  volumeOne: 'volume-1',
  volumeTwo: 'volume-2',
  volumeOff: 'volume-off',
  menu: 'menu',
  optionsVertical: 'options-vertical',
  options: 'options',
  arrowDown: 'arrow-down',
  arrowLeft: 'arrow-left',
  arrowRight: 'arrow-right',
  arrowUp: 'arrow-up',
  brightnessHigh: 'brightness_high',
};

export const DEFAULT_PATH: string = `${getBasePath()}/assets/icons.svg`;
