export declare type IconSize =
  | 'xx-small'
  | 'x-small'
  | 'small'
  | 'medium'
  | 'large'
  | 'x-large'
  | 'xx-large'
  | 'xxx-large'
  | 'xxxx-large';
export declare type IconType =
  | 'accessibility'
  | 'arrow-down'
  | 'arrow-down-circle'
  | 'arrow-left'
  | 'arrow-left-circle'
  | 'arrow-right'
  | 'arrow-right-circle'
  | 'arrow-up'
  | 'arrow-up-circle'
  | 'bell'
  | 'brightness_high'
  | 'brightness_low'
  | 'calendar'
  | 'check'
  | 'close'
  | 'cloud-download'
  | 'cloud-upload'
  | 'crop'
  | 'cursor-move'
  | 'equalizer'
  | 'eye'
  | 'eyeglass'
  | 'fire'
  | 'frame'
  | 'graduation'
  | 'grid'
  | 'home'
  | 'info'
  | 'layers'
  | 'link'
  | 'lock'
  | 'lock-open'
  | 'magnifier'
  | 'magnifier-add'
  | 'magnifier-remove'
  | 'menu'
  | 'microphone'
  | 'note'
  | 'options'
  | 'options-vertical'
  | 'paper-clip'
  | 'people'
  | 'pin'
  | 'question'
  | 'refresh'
  | 'reload'
  | 'screen-desktop'
  | 'screen-smartphone'
  | 'screen-tablet'
  | 'settings'
  | 'share'
  | 'shield'
  | 'size-actual'
  | 'size-fullscreen'
  | 'speech'
  | 'star'
  | 'trash'
  | 'user'
  | 'user-check'
  | 'user-plus'
  | 'user-remove'
  | 'volume-off'
  | 'volume-1'
  | 'volume-2'
  | 'x';

export const ICON_SIZES: { [key in IconSize]: IconSize } = {
  'xx-small': 'xx-small',
  'x-small': 'x-small',
  small: 'small',
  medium: 'medium',
  large: 'large',
  'x-large': 'x-large',
  'xx-large': 'xx-large',
  'xxx-large': 'xxx-large',
  'xxxx-large': 'xxxx-large',
};

export const ICON_TYPES: { [key in IconType]: IconType } = {
  accessibility: 'accessibility',
  'arrow-down': 'arrow-down',
  'arrow-down-circle': 'arrow-down-circle',
  'arrow-left': 'arrow-left',
  'arrow-left-circle': 'arrow-left-circle',
  'arrow-right': 'arrow-right',
  'arrow-right-circle': 'arrow-right-circle',
  'arrow-up': 'arrow-up',
  'arrow-up-circle': 'arrow-up-circle',
  bell: 'bell',
  brightness_high: 'brightness_high',
  brightness_low: 'brightness_low',
  calendar: 'calendar',
  check: 'check',
  close: 'close',
  'cloud-download': 'cloud-download',
  'cloud-upload': 'cloud-upload',
  crop: 'crop',
  'cursor-move': 'cursor-move',
  equalizer: 'equalizer',
  eye: 'eye',
  eyeglass: 'eyeglass',
  fire: 'fire',
  frame: 'frame',
  graduation: 'graduation',
  grid: 'grid',
  home: 'home',
  info: 'info',
  layers: 'layers',
  link: 'link',
  lock: 'lock',
  'lock-open': 'lock-open',
  magnifier: 'magnifier',
  'magnifier-add': 'magnifier-add',
  'magnifier-remove': 'magnifier-remove',
  menu: 'menu',
  microphone: 'microphone',
  note: 'note',
  options: 'options',
  'options-vertical': 'options-vertical',
  'paper-clip': 'paper-clip',
  people: 'people',
  pin: 'pin',
  question: 'question',
  refresh: 'refresh',
  reload: 'reload',
  'screen-desktop': 'screen-desktop',
  'screen-smartphone': 'screen-smartphone',
  'screen-tablet': 'screen-tablet',
  settings: 'settings',
  share: 'share',
  shield: 'shield',
  'size-actual': 'size-actual',
  'size-fullscreen': 'size-fullscreen',
  speech: 'speech',
  star: 'star',
  trash: 'trash',
  user: 'user',
  'user-check': 'user-check',
  'user-plus': 'user-plus',
  'user-remove': 'user-remove',
  'volume-off': 'volume-off',
  'volume-1': 'volume-1',
  'volume-2': 'volume-2',
  x: 'x',
};
