name: Continous Deployment

on:
  release:
    types:
      - published

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci
      - run: npx nx run-many --targets=build,storybook:build --projects=tags:package
      - run: npx nx run arc-publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: npx nx run components:storybook:deploy
        env:
          SWA_CLI_DEPLOYMENT_TOKEN: ${{ secrets.SWA_CLI_DEPLOYMENT_TOKEN }}
