name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - uses: nrwl/nx-set-shas@v3
      - run: nix develop
      - run: npm ci
      - run: npx nx run-many --target lint
      - run: npx nx run-many --target test
      - run: nix build .#components
      - run: nix build .#react
      - run: nix build .#storybook
