name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - run: nix develop
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - uses: nrwl/nx-set-shas@v3
      - run: nix run .#utils.x86_64-linux.clean-install
      - run: nix fmt && git diff --exit-code
      - run: npx nx affected --target=lint --parallel=3
      - run: npx nx affected --targets=build,build:storybook --parallel=3
      - run: npx nx affected --target=test --parallel=3
