name: Continuous Integration

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci
      - run: npx playwright install --with-deps
      - run: npx nx format:check --verbose
      - run: npx nx affected --target=lint --parallel=3
      - run: npx nx affected --target=build --parallel=3
      - run: npx nx affected --target=build:storybook --parallel=3
      - run: npx nx affected --target=test --parallel=3
