on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v12
        with:
          name: arup-group-arc-components
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix build .#documentation
      - run: nix develop --command npm ci --legacy-peer-deps
      - run: nix develop --command npx swa deploy -nu
        env:
          SWA_CLI_DEPLOY_ENV: production
          SWA_CLI_DEPLOYMENT_TOKEN: ${{ secrets.SWA_CLI_DEPLOYMENT_TOKEN }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
