name: Deploy Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - uses: nrwl/nx-set-shas@v3
      - run: nix develop
      - run: npm ci --legacy-peer-deps
      - run: npx nx run components:storybook:build
      - run: swa deploy -nu
        env:
          SWA_CLI_DEPLOY_ENV: production
          SWA_CLI_DEPLOYMENT_TOKEN: ${{ secrets.SWA_CLI_DEPLOYMENT_TOKEN }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
