name: dev
on:
  pull_request:
    branches: [dev]
  push:
    branches: [dev]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install Yarn
        uses: borales/actions-yarn@v2.3.0

      - name: Install node_modules
        run: yarn install

      - name: Test components
        run: yarn run test
