name: dev

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the dev branch
  pull_request:
    branches: [ dev ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16',
          cache: 'yarn'

      - name: Setup environment
        uses: borales/actions-yarn@v2.3.0
        with:
          node-version: 'lts/*'

      - name: Install packages
        run: yarn install

      - name: Test components
        run: yarn test
