name: Publish

on:
  release:
    types: [published]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      # - uses: aws-actions/configure-aws-credentials@master
      #   with:
      #     role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
      #     aws-region: ${{ secrets.AWS_REGION }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci
      - run: npx nx run-many --targets=build,storybook:build --projects=tags:package
      - run: npx nx run arc-publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      # - run: aws s3 sync ./dist/packages/storybook s3://${{ secrets.S3_BUCKET }}
