on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix develop
      - run: nix build .#components
      - name: npm publish
        run: publish --provenance --access public
        working-directory: ./result
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: nix build .#react
      - name: npm publish
        run: npm publish --provenance --access public
        working-directory: ./result
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
