on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix develop
      - run: npm set //registry.npmjs.org/:_authToken=$AUTH_TOKEN
        with:
          AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: nix build .#components
      - name: npm publish
        run: npm publish --access public
        working-directory: ./result
      - run: nix build .#react
      - name: npm publish
        run: npm publish --access public
        working-directory: ./result
