name: publish
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'

      - name: Install Yarn
        uses: borales/actions-yarn@v2.3.0

      - name: Install node_modules
        run: yarn install

      - name: Test components
        run: yarn run test

      - name: Build ARC
        run: sudo yarn run build

      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
