on:
  workflow_dispatch:

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix develop
      - run: setup-npm-config
      - run: nix build .#components
      - name: publish @arc-web/components
        run: |
          cd result \
          && npm publish --access public
      - run: rm -rf result
      - run: nix build .#react
      - name: publish @arc-web/react
        run: |
          cd result \
          && npm publish --access public
