on:
  workflow_dispatch:

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix develop --command setup-npm-config
      - run: mkdir publish
      - run: nix build .#components
      - run: cp -r result/* publish
      - name: publish @arc-web/components
        run: nix develop --command npm publish publish/ --access public
      - run: sudo rm -rf publish result
      - run: mkdir publish
      - run: nix build .#react
      - run: cp -r result/* publish
      - name: publish @arc-web/react
        run: nix develop --command npm publish publish/ --access public
