on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v12
        with:
          name: arup-group-arc-components
          signingKey: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: nix develop --command generate-sbom
      - uses: actions/upload-artifact@v4
        with:
          path: sbom.zip
          name: SBOM
