on:
  workflow_dispatch:
  release:

jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v14
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - run: nix develop --command generate-sbom
      - uses: actions/upload-artifact@v4
        with:
          path: sbom.zip
          name: SBOM
